### ISSUE TITLE
How can I run this project? What are the requirements?

### ISSUE THREAD

**Issue by miguelvalente** [Vlad-2299/CellularAutomation#1]

**Comment by Vlad-2299** [comment]
Please find the instructions in the recently updated README file. Ensure you install the requirements through pip and ffmpeg via their official website. To replicate the results, execute 'cells.py' and select which simulation you want to generate ('seeds' or 'bbrain'), specify the number of generations, and set the dimensions of the window. You can also save the output as a video by setting '--save_video' to True.
